version: '3.1'
services:
  app:
    container_name: app-java-demo
    image: app-java-demo
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=contacts