version: '3.1'
services:
  app:
    container_name: app-java-demo
    image: app-java-demo
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    build: ./
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=contacts